language: r
cache: packages

notifications:
  email:
    recipients:
     - alerts@jumpingrivers.support
    on_success: change
    on_failure: change
env:
  global:
    - ALLOWED_NOTES=1

r_packages:
  - drat


r_github_packages:
  - jumpingrivers/inteRgrate

before_install:
  - sudo apt-get install -y ghostscript

before_script:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/test_deploy.sh
  - bash test_deploy.sh && rm test_deploy.sh

script:
  - Rscript -e "inteRgrate::check_pkg()"
  - Rscript -e "inteRgrate::check_r_filenames()"
  - Rscript -e "inteRgrate::check_tidy_description()"
  - Rscript -e "inteRgrate::check_lintr()"
  - Rscript -e "inteRgrate::check_namespace()"

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
